name: bidenv
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - bzip2
  - ca-certificates
  - libffi
  - ncurses
  - openssl
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
      - annotated-types==0.7.0
      - anyio==4.4.0
      - beautifulsoup4==4.12.3
      - certifi==2024.6.2
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - distro==1.9.0
      - et-xmlfile==1.1.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - joblib==1.4.2
      - markdown==3.6
      - numpy==1.26.4
      - openai==1.34.0
      - openpyxl==3.1.4
      - pandas==2.2.2
      - pillow==10.3.0
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pymupdf==1.24.5
      - pymupdfb==1.24.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - reportlab==4.2.0
      - requests==2.32.3
      - retrying==1.3.4
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - threadpoolctl==3.5.0
      - tqdm==4.66.4
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.1
